import type { Metadata } from "next";
import "./globals.css";

import { lobster, bungeeShade, indieFlower, anonymousPro, playfair } from "../utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lobster.variable} ${bungeeShade.variable} ${indieFlower.variable} ${anonymousPro.variable}`}>{children}</body>
    </html>
  );
}
